ruby '3.2.2'

# Check if ruby version is matching ruby specification in line 1
raise "Ruby 3.2.2 is required, but you're using Ruby #{RUBY_VERSION}. Please use Ruby 3.2.2." unless RUBY_VERSION == "3.2.2"

source "https://rubygems.org"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'bundler', '2.4.18'
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1', '!= 1.15.2'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
gem 'xcodeproj', '< 1.26.0'
gem 'bigdecimal', '!= 3.3.1'
gem 'concurrent-ruby', '< 1.3.4'
